#!/bin/bash

# Define command-line arguments
RESOURCE_TYPE=$1
NAMESPACE=$2

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n --all-namespaces | tail -n +2 | while read line; do
    # Extract CPU and memory usage from the output
    NAME=$(echo $line | awk '{print $1}')
    CPU=$(echo $line | awk '{print $2}')
    MEMORY=$(echo $line | awk '{print $3}')

    # Output the statistics to the console
    printf "%-15s %-15s %-15s %-10s %-10s\n" "Resource" "Namespace" "Name" "CPU" "Memory"
    printf "%-15s %-15s %-15s %-10s %-10s\n" "$RESOURCE_TYPE" "$NAMESPACE" "$NAME" "$CPU" "$MEMORY"
done
